create table "public"."profile" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "user_id" uuid not null,
    "tenent_id" uuid,
    "status" bigint not null default '1'::bigint,
    "level" bigint not null default '2'::bigint
);


alter table "public"."profile" enable row level security;

CREATE UNIQUE INDEX profile_pkey ON public.profile USING btree (id);

alter table "public"."profile" add constraint "profile_pkey" PRIMARY KEY using index "profile_pkey";

alter table "public"."profile" add constraint "profile_tenent_id_fkey" FOREIGN KEY (tenent_id) REFERENCES tenent(id) not valid;

alter table "public"."profile" validate constraint "profile_tenent_id_fkey";

alter table "public"."profile" add constraint "profile_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."profile" validate constraint "profile_user_id_fkey";


