create table "public"."commitment" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "title" character varying not null,
    "description" text,
    "start_at" timestamp with time zone not null,
    "end_at" timestamp with time zone,
    "status" bigint not null default '1'::bigint
);


alter table "public"."commitment" enable row level security;

alter table "public"."tenent" alter column "name" set data type text using "name"::text;

CREATE UNIQUE INDEX commitment_pkey ON public.commitment USING btree (id);

alter table "public"."commitment" add constraint "commitment_pkey" PRIMARY KEY using index "commitment_pkey";


